// main/client/ui/src/index.ts
// Shared UI components for the web app template.

// Elements - Atomic UI building blocks
export {
  Alert,
  Avatar,
  Badge,
  Box,
  Button,
  Checkbox,
  CloseButton,
  Divider,
  EnvironmentBadge,
  FileInput,
  Heading,
  IconButton,
  Input,
  Kbd,
  MenuItem,
  OAuthButton,
  PasswordInput,
  Progress,
  Skeleton,
  SkipLink,
  Spinner,
  Switch,
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableFooter,
  TableHead,
  TableHeader,
  TableRow,
  Text,
  TextArea,
  Toaster,
  Tooltip,
  VersionBadge,
  VisuallyHidden,
} from './elements';

// Components - Composed multi-part components
export {
  Accordion,
  AuthFormLayout,
  Card,
  CardAsyncState,
  DelayedFallback,
  DeviceRowCard,
  Dialog,
  Dropdown,
  EmptyState,
  ErrorBoundary,
  FeatureHint,
  FocusTrap,
  FormField,
  Image,
  JobStatusBadge,
  LabeledValueRow,
  // Billing
  InvoiceList,
  InvoiceRow,
  LoadingContainer,
  Markdown,
  MediaGallery,
  MetricValue,
  Pagination,
  PaymentMethodCard,
  PeekLink,
  PlanCard,
  PlanChangeDialog,
  Popover,
  ProfileCompletenessCard,
  PricingTable,
  Radio,
  RadioGroup,
  RoleBadge,
  Select,
  SessionCard,
  Slider,
  SectionErrorBoundary,
  StatusBadge,
  getUserStatus,
  SubscriptionStatus,
  Tabs,
  Toast,
  ToastContainer,
  TitledCardSection,
  UsageBar,
  UsageSummary,
  buildDefaultUsageMetrics,
} from './components';
export type {
  CardAsyncStateProps,
  DelayedFallbackProps,
  DeviceRowCardDevice,
  DeviceRowCardProps,
  EmptyStateProps,
  ErrorBoundaryProps,
  FeatureHintProps,
  JobStatusBadgeProps,
  LabeledValueRowProps,
  MediaGalleryItem,
  MediaGalleryProps,
  InvoiceListProps,
  InvoiceRowProps,
  MetricValueProps,
  PaymentMethodCardProps,
  PeekLinkProps,
  PlanCardProps,
  PlanChangeDialogProps,
  ProfileCompletenessCardProps,
  PricingTableProps,
  RoleBadgeProps,
  SessionCardProps,
  SessionCardSession,
  SubscriptionStatusProps,
  StatusBadgeProps,
  TabItem,
  TitledCardSectionProps,
  TabsProps,
  SectionErrorBoundaryProps,
  UsageBarProps,
  UsageMetric,
  UsageSummaryProps,
} from './components';

// Layouts - Page and section layouts
export {
  AppShell,
  AuthLayout,
  BottombarLayout,
  Container,
  LeftSidebarLayout,
  Modal,
  Overlay,
  PageContainer,
  ProtectedRoute,
  ResizablePanel,
  ResizablePanelGroup,
  ResizableSeparator,
  RightSidebarLayout,
  ScrollArea,
  SidePeek,
  StackedLayout,
  TopbarLayout,
} from './layouts';
export type {
  AppShellProps,
  BottombarLayoutProps,
  LeftSidebarLayoutProps,
  ModalHeightMode,
  ModalSize,
  RightSidebarLayoutProps,
  SidePeekRootProps,
  SidePeekSize,
  TopbarLayoutProps,
} from './layouts';

// Theme
export {
  ThemeProvider,
  breakpoints,
  colors,
  contentMaxWidth,
  darkColors,
  lightColors,
  motion,
  radius,
  spacing,
  touchTargetSize,
  typography,
  useTheme,
} from './theme';
export type {
  Breakpoints,
  ContrastMode,
  DarkColors,
  Density,
  LightColors,
  Radius,
  ThemeColors,
  ThemeContextValue,
  ThemeProviderProps,
} from './theme';

// Utilities
export { cn, parseMarkdown, safeHref } from './utils';
export type { MarkdownBlock, MarkdownSpan } from './utils';
