// main/shared/src/modules/comms/index.ts
/**
 * Communication Shared Utilities
 *
 * This module provides unified abstractions for email, notifications,
 * SMS, and webhooks.
 *
 * @module Modules/Comms
 */

export {
  createEmailLogEntrySchema,
  createEmailTemplateSchema,
  emailLogEntrySchema,
  emailProviderSchema,
  emailStatusSchema,
  emailTemplateSchema,
  type CreateEmailLogEntry,
  type CreateEmailTemplate,
  type EmailLogEntry,
  type EmailProvider,
  type EmailStatus,
  type EmailTemplate,
  type UpdateEmailTemplate,
  updateEmailTemplateSchema,
} from './email';

export {
  baseMarkAsReadRequestSchema,
  DEFAULT_NOTIFICATION_PREFERENCES,
  deleteNotificationResponseSchema,
  getNotificationLevelTone,
  InvalidPreferencesError,
  InvalidSubscriptionError,
  markReadResponseSchema,
  NOTIFICATION_CHANNELS,
  NOTIFICATION_LEVELS,
  NOTIFICATION_LEVEL_MAP,
  NOTIFICATION_PRIORITIES,
  NOTIFICATION_TYPES,
  notificationDeleteRequestSchema,
  notificationPreferencesSchema,
  NotificationRateLimitError,
  notificationSchema,
  NotificationsDisabledError,
  NotificationSendError,
  notificationsListRequestSchema,
  notificationsListResponseSchema,
  PayloadTooLargeError,
  PreferencesNotFoundError,
  preferencesResponseSchema,
  ProviderError,
  ProviderNotConfiguredError,
  QuietHoursActiveError,
  sendNotificationRequestSchema,
  sendNotificationResponseSchema,
  shouldSendNotification,
  subscribeRequestSchema,
  subscribeResponseSchema,
  SubscriptionExistsError,
  SubscriptionExpiredError,
  SubscriptionNotFoundError,
  type BaseMarkAsReadRequest,
  type BatchSendResult,
  type DeleteNotificationResponse,
  type MarkReadResponse,
  type Notification,
  type NotificationAction,
  type NotificationChannel,
  type NotificationDeleteRequest,
  type NotificationLevel,
  type NotificationMessage,
  type NotificationPayload,
  type NotificationPreferences,
  type NotificationPreferencesConfig,
  type NotificationPriority,
  type NotificationsListRequest,
  type NotificationsListResponse,
  type NotificationType,
  type NotificationTypePreference,
  type PreferencesResponse,
  type SendResult,
  type PushSubscription,
  type PushSubscriptionKeys,
  type SendNotificationRequest,
  type SendNotificationResponse,
  type StoredPushSubscription,
  type SubscribeRequest,
  type SubscribeResponse,
  type UnsubscribeRequest,
  type UnsubscribeResponse,
  type UpdatePreferencesRequest,
  type VapidKeyResponse,
  unsubscribeRequestSchema,
  unsubscribeResponseSchema,
  updatePreferencesRequestSchema,
  vapidKeyResponseSchema,
  VapidNotConfiguredError,
} from './notifications';

export { type SmsConfig, type SmsOptions, type SmsProvider, type SmsResult } from './sms';

export {
  calculateRetryDelay,
  createWebhookDeliverySchema,
  createWebhookSchema,
  deliveryListResponseSchema,
  deliveryReplayResponseSchema,
  isDeliveryTerminal,
  matchesEventFilter,
  rotateSecretResponseSchema,
  shouldRetryDelivery,
  type CreateWebhook,
  type CreateWebhookDelivery,
  type DeliveryListResponse,
  type DeliveryReplayResponse,
  type RotateSecretResponse,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type Webhook,
  type WebhookDeleteResponse,
  type WebhookDelivery,
  type WebhookDeliveryItem,
  type WebhookDeliveryStatus,
  type WebhookEventType,
  type WebhookItem,
  type WebhookListResponse,
  type WebhookMutationResponse,
  type WebhookResponse,
  type WebhookWithDeliveries,
  updateWebhookDeliverySchema,
  updateWebhookSchema,
  webhookDeleteResponseSchema,
  webhookDeliveryItemSchema,
  webhookDeliverySchema,
  webhookItemSchema,
  webhookListResponseSchema,
  webhookMutationResponseSchema,
  webhookResponseSchema,
  webhookSchema,
  webhookWithDeliveriesSchema,
} from './webhooks';
