// main/tools/features/manifest.ts
import { createHash } from 'node:crypto';

export interface FeatureManifest {
  schemaVersion: 1;
  id: string;
  name: string;
  version: string;
  coreVersion: string;
  files: Record<string, string>;
}
export const sha256 = (value: string | Buffer): string =>
  createHash('sha256').update(value).digest('hex');
export const json = (value: unknown): string => JSON.stringify(value, null, 2) + '\n';
export function object(value: unknown): Record<string, unknown> {
  if (value === null || typeof value !== 'object' || Array.isArray(value))
    throw new Error('Expected a JSON object.');
  return value as Record<string, unknown>;
}
export function featureId(value: unknown): asserts value is string {
  if (
    typeof value !== 'string' ||
    value.length > 48 ||
    !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(value)
  )
    throw new Error('Invalid feature ID. Use lowercase words separated by hyphens.');
}
export function sourcePath(value: string): void {
  if (
    !/^(web|server)\/(?:[a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_-]+\.(ts|tsx|css|json)$/.test(value) ||
    value.split('/').some((part) => /^(con|prn|aux|nul|com[0-9]|lpt[0-9])(?:\.|$)/i.test(part))
  )
    throw new Error(`Unsupported feature source path: ${value}`);
}
export function manifest(value: unknown): FeatureManifest {
  const m = object(value);
  if (
    Object.keys(m).sort().join(',') !== 'coreVersion,files,id,name,schemaVersion,version' ||
    m['schemaVersion'] !== 1
  )
    throw new Error('Unsupported feature manifest. Version 1 accepts source files only.');
  featureId(m['id']);
  if (
    typeof m['name'] !== 'string' ||
    !m['name'].trim() ||
    m['name'].length > 80 ||
    [...m['name']].some((char) => char.charCodeAt(0) < 32)
  )
    throw new Error('Invalid feature name.');
  for (const field of ['version', 'coreVersion']) {
    if (typeof m[field] !== 'string' || !/^\d+\.\d+\.\d+$/.test(m[field]))
      throw new Error(`Use an exact release version for ${field}.`);
  }
  const files = object(m['files']);
  if (Object.keys(files).length < 1 || Object.keys(files).length > 200)
    throw new Error('A feature must contain between 1 and 200 files.');
  const folded = new Set<string>();
  for (const [file, hash] of Object.entries(files)) {
    sourcePath(file);
    if (folded.has(file.toLowerCase())) throw new Error(`Case-insensitive path collision: ${file}`);
    folded.add(file.toLowerCase());
    if (typeof hash !== 'string' || !/^[a-f0-9]{64}$/.test(hash))
      throw new Error(`Invalid hash: ${file}`);
  }
  for (const side of ['web', 'server']) {
    if (
      Object.keys(files).some((file) => file.startsWith(`${side}/`)) &&
      files[`${side}/index.${side === 'web' ? 'tsx' : 'ts'}`] === undefined
    )
      throw new Error(`Missing ${side} entry point.`);
  }
  return m as unknown as FeatureManifest;
}
export function sameFeature(a: FeatureManifest, b: FeatureManifest): boolean {
  return (
    a.id === b.id &&
    a.name === b.name &&
    a.version === b.version &&
    a.coreVersion === b.coreVersion &&
    Object.keys(a.files).length === Object.keys(b.files).length &&
    Object.entries(a.files).every(([file, hash]) => b.files[file] === hash)
  );
}
export const STATE_PATH = 'features.lock.json';
export const SERVER_REGISTRY = 'main/apps/server/src/extensions/installed.ts';
export const WEB_REGISTRY = 'main/apps/web/src/extensions/installed.tsx';
export function destination(id: string, source: string): string {
  featureId(id);
  sourcePath(source);
  const [side, ...parts] = source.split('/');
  return `main/apps/${side}/src/extensions/packs/${id}/${parts.join('/')}`;
}
export function registries(features: readonly FeatureManifest[]): Record<string, string> {
  const sorted = [...features].sort((a, b) => a.id.localeCompare(b.id));
  const server = sorted.filter((m) => m.files['server/index.ts'] !== undefined);
  const web = sorted.filter((m) => m.files['web/index.tsx'] !== undefined);
  const header =
    '// Generated by features:add / features:remove. Keep custom code outside this file.\n';
  return {
    [SERVER_REGISTRY]:
      header +
      "import type { InstalledServerFeature } from './types';\n" +
      server
        .map((m, i) => `import { routes as routes${i} } from './packs/${m.id}/index';\n`)
        .join('') +
      server
        .flatMap((m, i) =>
          m.files['server/webhooks.ts'] === undefined
            ? []
            : [`import { webhooks as webhooks${i} } from './packs/${m.id}/webhooks';\n`],
        )
        .join('') +
      `export const installedFeatures: readonly InstalledServerFeature[] = [\n` +
      server
        .map(
          (m, i) =>
            `  { id: ${JSON.stringify(m.id)}, routes: routes${i}${m.files['server/webhooks.ts'] === undefined ? '' : `, webhooks: webhooks${i}`} },\n`,
        )
        .join('') +
      '];\n',
    [WEB_REGISTRY]:
      header +
      "import type { InstalledWebFeature } from './types';\n" +
      web.map((m, i) => `import Page${i} from './packs/${m.id}/index';\n`).join('') +
      `export const installedFeatures: readonly InstalledWebFeature[] = [\n` +
      web
        .map(
          (m, i) =>
            `  { id: ${JSON.stringify(m.id)}, name: ${JSON.stringify(m.name)}, Page: Page${i} },\n`,
        )
        .join('') +
      '];\n',
  };
}
