// main/shared/src/modules/db/search/index.ts

export {
  InvalidCursorError,
  InvalidFieldError,
  InvalidFilterError,
  InvalidOperatorError,
  InvalidPaginationError,
  InvalidQueryError,
  InvalidSortError,
  isInvalidFilterError,
  isInvalidQueryError,
  isSearchError,
  isSearchProviderError,
  isSearchTimeoutError,
  QueryTooComplexError,
  SearchError,
  SearchProviderError,
  SearchProviderUnavailableError,
  SearchTimeoutError,
  UnsupportedOperatorError,
  type SearchErrorType,
} from './errors';

export {
  isCompoundFilter,
  isFilterCondition,
  type CompoundFilter,
  type CursorSearchResult,
  type FacetBucket,
  type FacetConfig,
  type FacetedSearchQuery,
  type FacetedSearchResult,
  type FacetResult,
  type FilterCondition,
  type FilterOperator,
  type FilterPrimitive,
  type FilterValue,
  type FullTextSearchConfig,
  type HighlightedField,
  type LogicalOperator,
  type SearchCapabilities,
  type SearchProvider,
  type SearchQuery,
  type SearchResult,
  type SearchResultItem,
  type SortConfig,
  type SortOrder,
} from './types';

export {
  compoundFilterSchema,
  cursorSearchResultSchema,
  facetBucketSchema,
  facetConfigSchema,
  facetedSearchQuerySchema,
  facetedSearchResultSchema,
  facetResultSchema,
  filterConditionSchema,
  filterOperatorSchema,
  filterSchema,
  filterValueSchema,
  fullTextSearchConfigSchema,
  highlightedFieldSchema,
  logicalOperatorSchema,
  rangeValueSchema,
  searchQuerySchema,
  searchResultItemSchema,
  searchResultSchema,
  sortConfigSchema,
  urlSearchParamsSchema,
  type RangeValue,
  type SearchQueryInput,
  type SearchQueryOutput,
  type UrlSearchParams,
  type UrlSearchParamsInput,
  filterPrimitiveSchema,
} from './schemas';

export {
  createSearchQuery,
  contains,
  eq,
  fromSearchQuery,
  gt,
  inArray,
  lt,
  neq,
  SearchQueryBuilder,
  type FilterGroupBuilder,
} from './query.builder';
