// main/server/system/src/index.ts
/**
 * Internal compatibility barrel for in-repo relative imports.
 * Public package consumers should use scoped subpaths.
 */

export {
  DEFAULT_CACHE_CONFIG,
  LRUCache,
  MemoryCacheProvider,
  RedisCacheProvider,
  createCache,
  createCacheFromEnv,
  createMemoryCache,
  createRedisCache,
  createRedisProvider,
  loadCacheConfig,
  type BaseCacheConfig,
  type CacheConfig,
  type CacheDeleteOptions,
  type CacheEntry,
  type CacheEntryMetadata,
  type CacheEvictionReason,
  type CacheGetOptions,
  type CacheLogger,
  type CacheOperationResult,
  type CacheProvider,
  type CacheSetOptions,
  type CacheStats,
  type CreateCacheOptions,
  type EvictionCallback,
  type EvictionReason,
  type LRUCacheOptions,
  type MemoizeOptions,
  type MemoizeStats,
  type MemoizedFunction,
  type MemoryCacheConfig,
  type RedisCacheConfig,
} from './cache';
export {
  createHttpErrorResponse,
  mapErrorToHttpResponse,
  toHttpErrorResponse,
  type ErrorMapperLogger,
  type ErrorMapperOptions,
  type HttpErrorResponse,
  type ToHttpErrorOptions,
} from './errors';
export {
  USE_COLOR,
  colorize,
  createJobCorrelationId,
  createJobLogger,
  createLogger,
  createRequestLogger,
  developmentFormatter,
  levelToColor,
  nowHHMMSS,
  padLevel,
  serializeError,
  type ColorName,
  type Logger,
} from './logger';
export {
  ConsoleErrorTrackingProvider,
  MetricsCollector,
  NoopErrorTrackingProvider,
  addBreadcrumb,
  captureError,
  createErrorTracker,
  formatPrometheusMetrics,
  getMetricsCollector,
  initSentry,
  resetMetricsCollector,
  setUserContext,
  type Breadcrumb,
  type BreadcrumbLevel,
  type ErrorContext,
  type ErrorTrackingConfig,
  type ErrorTrackingProvider,
  type MetricsSummary,
} from './observability';
export {
  clearRegistry,
  createLogRequestContext,
  createRouteMap,
  createScopedRouteHelpers,
  extractTraceId,
  generateCorrelationId,
  getAuthenticatedUser,
  getOrCreateCorrelationId,
  getRegisteredRoutes,
  isValidCorrelationId,
  protectedRoute,
  publicRoute,
  registerRoute,
  registerRouteMap,
  requireAuthenticatedUser,
  withRouteOptions,
  withRoutePreHandlers,
  type AuthGuardFactory,
  type HandlerContext,
  type HttpMethod,
  type HttpReply,
  type HttpRequest,
  type JsonSchemaObject,
  type RouteDefinition,
  type RouteDeprecation,
  type RouteHandler,
  type RouteMap,
  type RouteOpenApiMeta,
  type RoutePreHandler,
  type RouteRegistryEntry,
  type RouteResult,
  type RouteSchema,
  type RouterOptions,
  type ScopedRouteHandler,
  type ValidationSchema,
} from './http';
export {
  IpBlocklist,
  JwtError,
  MemoryStore,
  RateLimitPresets,
  RateLimiter,
  RedisRateLimitStore,
  TOKEN_LENGTH,
  createIpBlocklist,
  createIpBlocklistMiddleware,
  createRateLimiter,
  decode,
  decryptToken,
  encryptToken,
  generateToken,
  isInCidrRange,
  isSafePath,
  parseCidr,
  sign,
  signToken,
  validateCsrfToken,
  verify,
  verifyToken,
  type ClientRecord,
  type CsrfValidationOptions,
  type IpBlocklistConfig,
  type IpPolicyLevel,
  type IpReputationProvider,
  type IpReputationResult,
  type JwtErrorCode,
  type JwtHeader,
  type JwtPayload,
  type MemoryStoreConfig,
  type MemoryStoreStats,
  type RateLimitInfo,
  type RateLimitStore,
  type RateLimiterConfig,
  type RateLimiterStats,
  type RedisRateLimitStoreConfig,
  type SignOptions,
  type VerifyOptions,
} from './security';
export {
  checkCacheStatus,
  checkDbStatus,
  checkEmailStatus,
  checkPubSubStatus,
  checkQueueStatus,
  checkRateLimitStatus,
  checkSchemaStatus,
  checkStorageStatus,
  checkWebSocketStatus,
  getDetailedHealth,
  isPortFree,
  isPortListening,
  logStartupSummary,
  pickAvailablePort,
  uniquePorts,
  waitForPort,
  type DetailedHealthOptions,
  type HealthContext,
  type SchemaValidatorFn,
} from './runtime';
