// main/shared/src/contracts/contract.tasks.ts
/**
 * Generated by pnpm starter:feature.
 * Own this file in your product fork.
 */

import {
  createTaskRequestSchema,
  taskMutationResponseSchema,
  tasksListResponseSchema,
  updateTaskRequestSchema,
} from '../modules/core/tasks';
import { emptyBodySchema, errorResponseSchema } from '../modules/system';
import { uuidSchema } from '../schema';

import type { Contract } from '../api/api';

export const tasksContract = {
  list: {
    method: 'GET' as const,
    path: '/api/tasks',
    responses: {
      200: tasksListResponseSchema,
      401: errorResponseSchema,
    },
    summary: 'List tasks for the authenticated user',
  },

  create: {
    method: 'POST' as const,
    path: '/api/tasks/create',
    body: createTaskRequestSchema,
    responses: {
      200: taskMutationResponseSchema,
      400: errorResponseSchema,
      401: errorResponseSchema,
    },
    summary: 'Create task',
  },

  update: {
    method: 'POST' as const,
    path: '/api/tasks/:id/update',
    pathParams: { id: uuidSchema },
    body: updateTaskRequestSchema,
    responses: {
      200: taskMutationResponseSchema,
      400: errorResponseSchema,
      401: errorResponseSchema,
      404: errorResponseSchema,
    },
    summary: 'Update task',
  },

  delete: {
    method: 'POST' as const,
    path: '/api/tasks/:id/delete',
    pathParams: { id: uuidSchema },
    body: emptyBodySchema,
    responses: {
      200: taskMutationResponseSchema,
      401: errorResponseSchema,
      404: errorResponseSchema,
    },
    summary: 'Delete task',
  },
} satisfies Contract;
