// main/shared/src/modules/core/admin/index.ts
/**
 * Admin Domain
 *
 * Provides schemas and contracts for system monitoring, user management, and maintenance.
 * @module Domain/Admin
 */

export {
  formatSecurityEventType,
  getAppRoleLabel,
  getAppRoleTone,
  getSecuritySeverityTone,
  getUserStatusLabel,
  getUserStatusTone,
} from './admin.display';

export {
  ADMIN_AUDIT_EVENTS_DEFAULT_LIMIT,
  ADMIN_AUDIT_EVENTS_MAX_LIMIT,
  ADMIN_LIST_MAX_OFFSET,
  ADMIN_ROUTE_METHODS,
  ADMIN_TENANTS_DEFAULT_LIMIT,
  ADMIN_TENANTS_MAX_LIMIT,
  ADMIN_USER_SEARCH_DEFAULT_LIMIT,
  ADMIN_USER_SEARCH_MAX_LIMIT,
  ADMIN_WEBHOOKS_DEFAULT_LIMIT,
  ADMIN_WEBHOOKS_MAX_LIMIT,
  ADMIN_WEBHOOK_DELIVERIES_DEFAULT_LIMIT,
  ADMIN_WEBHOOK_DELIVERIES_MAX_LIMIT,
  adminAuditEventsQuerySchema,
  adminTenantListQuerySchema,
  adminUserSearchQuerySchema,
  adminWebhookDeliveryListQuerySchema,
  adminWebhookListQuerySchema,
  LOCKOUT_DURATION_MINUTES,
  MAX_LOCKOUT_DURATION_MINUTES,
  USER_STATUSES,
  adminActionResponseSchema,
  adminCreateUserRequestSchema,
  adminDeleteUserRequestSchema,
  adminResetPasswordRequestSchema,
  adminForceLogoutRequestSchema,
  adminForceLogoutResponseSchema,
  adminHardBanRequestSchema,
  adminHardBanResponseSchema,
  routeManifestEntrySchema,
  adminLockUserRequestSchema,
  adminLockUserResponseSchema,
  adminSuspendTenantRequestSchema,
  adminTenantDetailSchema,
  adminTenantListResponseSchema,
  adminTenantStateChangeResponseSchema,
  adminTenantSchema,
  adminTenantsListResponseSchema,
  adminWebhookDeliveryListResponseSchema,
  adminWebhookDeliverySchema,
  adminWebhookListResponseSchema,
  adminWebhookReplayResponseSchema,
  adminWebhookSchema,
  adminUpdateUserRequestSchema,
  adminUpdateUserResponseSchema,
  adminUserListFiltersSchema,
  adminUserListResponseSchema,
  adminUserSchema,
  endImpersonationRequestSchema,
  endImpersonationResponseSchema,
  impersonationResponseSchema,
  routeManifestResponseSchema,
  systemStatsResponseSchema,
  unlockAccountRequestSchema,
  userStatusSchema,
} from './admin.schemas';

export type {
  AdminActionResponse,
  AdminCreateUserRequest,
  AdminDeleteUserRequest,
  AdminResetPasswordRequest,
  AdminForceLogoutRequest,
  AdminForceLogoutResponse,
  AdminHardBanRequest,
  AdminHardBanResponse,
  AdminRouteManifestEntry,
  AdminRouteMethod,
  AdminLockUserRequest,
  AdminLockUserResponse,
  AdminSuspendTenantRequest,
  AdminTenantDetail,
  AdminTenantListQuery,
  AdminTenantListResponse,
  AdminTenantStateChangeResponse,
  AdminTenant,
  AdminWebhook,
  AdminWebhookDelivery,
  AdminWebhookDeliveryListQuery,
  AdminWebhookDeliveryListResponse,
  AdminWebhookListQuery,
  AdminWebhookListResponse,
  AdminAuditEventsQuery,
  AdminWebhookReplayResponse,
  AdminUpdateUserRequest,
  AdminUpdateUserResponse,
  AdminUser,
  AdminUserListFilters,
  AdminUserListResponse,
  AdminUserSearchQuery,
  EndImpersonationRequest,
  EndImpersonationResponse,
  ImpersonationResponse,
  RouteManifestResponse,
  SystemStatsResponse,
  UnlockAccountRequest,
  UserStatus,
} from './admin.schemas';

export {
  SECURITY_EVENT_TYPES,
  SECURITY_SEVERITIES,
  securityEventDetailRequestSchema,
  securityEventDetailResponseSchema,
  securityEventSchema,
  securityEventsExportRequestSchema,
  securityEventsExportResponseSchema,
  securityEventsFilterSchema,
  securityEventsListRequestSchema,
  securityEventsListResponseSchema,
  securityMetricsRequestSchema,
  securityMetricsResponseSchema,
  securityMetricsSchema,
  type SecurityEvent,
  type SecurityEventDetailRequest,
  type SecurityEventDetailResponse,
  type SecurityEventType,
  type SecurityEventsExportRequest,
  type SecurityEventsExportResponse,
  type SecurityEventsFilter,
  type SecurityEventsListRequest,
  type SecurityEventsListResponse,
  type SecurityMetrics,
  type SecurityMetricsRequest,
  type SecurityMetricsResponse,
  type SecuritySeverity,
} from './admin.security.schemas';
