// main/shared/src/modules/realtime/index.ts

export {
  applyOperation,
  applyOperations,
  checkVersionConflicts,
  conflictResponseSchema,
  getOperationPointers,
  getRecordsRequestSchema,
  getRecordsResponseSchema,
  isFieldMutable,
  listInsertOperationSchema,
  listPositionSchema,
  listRemoveOperationSchema,
  operationSchema,
  PROTECTED_FIELDS,
  realtimeContract,
  REALTIME_ERRORS,
  recordMapSchema,
  recordPointerSchema,
  recordSchema,
  setNowOperationSchema,
  setOperationSchema,
  setPath,
  transactionSchema,
  writeResponseSchema,
  type ApplyOperationsResult,
  type ConflictResponse,
  type GetRecordsRequest,
  type GetRecordsResponse,
  type ListPosition,
  type RealtimeListInsertOperation,
  type RealtimeListRemoveOperation,
  type RealtimeOperation,
  type RealtimeRecord,
  type RealtimeSetNowOperation,
  type RealtimeSetOperation,
  type RealtimeTransaction,
  type RecordMap,
  type RecordPointer,
  type VersionConflict,
  type VersionedRecord,
  type WriteResponse,
  // Sprint 7.1 type aliases
  type ReadTransaction,
  type WriteTransaction,
} from './realtime';
