// main/client/react/src/stores/toastStore.ts
import { createStore } from './createStore';

/** Visual tone for toast notification styling */
export type ToastTone = 'info' | 'success' | 'danger' | 'warning';

/**
 * Represents a single toast notification message.
 *
 * @param id - Unique identifier for the toast (auto-generated by the store)
 * @param title - Optional heading text
 * @param description - Optional body text
 * @param tone - Visual tone variant (defaults to 'info' at render time)
 */
export type ToastMessage = {
  id: string;
  title?: string;
  description?: string;
  tone?: ToastTone;
  action?: { label: string; onClick: () => void };
};

type ToastState = {
  messages: ToastMessage[];
  show: (msg: Omit<ToastMessage, 'id'>) => void;
  dismiss: (id: string) => void;
};

export const toastStore = createStore<ToastState>((set) => ({
  messages: [],
  show: (msg): void => {
    set((state) => ({
      messages: [...state.messages, { id: crypto.randomUUID(), ...msg }],
    }));
  },
  dismiss: (id): void => {
    set((state) => ({
      messages: state.messages.filter((m) => m.id !== id),
    }));
  },
}));
