// Generated by features:add / features:remove. Keep custom code outside this file.
import type { InstalledWebFeature } from './types';
export const installedFeatures: readonly InstalledWebFeature[] = [
];
