// main/shared/src/modules/core/tasks/tasks.schemas.ts
/**
 * Generated by pnpm starter:feature.
 * Own this file in your product fork.
 */

import {
  createArraySchema,
  createSchema,
  isoDateTimeSchema,
  parseBoolean,
  parseObject,
  parseOptional,
  parseString,
  uuidSchema,
} from '../../../schema';

import type { Schema } from '../../../schema';

export interface Task {
  readonly id: string;
  readonly ownerId: string;
  readonly title: string;
  readonly completed: boolean;
  readonly createdAt: string;
  readonly updatedAt: string;
}

export interface CreateTaskRequest {
  readonly title: string;
}

export interface UpdateTaskRequest {
  readonly title?: string | undefined;
  readonly completed?: boolean | undefined;
}

export interface TasksListResponse {
  readonly tasks: readonly Task[];
}

export interface TaskMutationResponse {
  readonly task: Task;
}

function parseTitle(data: unknown): string {
  const title = parseString(data, 'title').trim();
  if (title.length === 0) throw new Error('title is required');
  if (title.length > 120) throw new Error('title must be at most 120 characters');
  return title;
}

export const taskSchema: Schema<Task> = createSchema((data: unknown) => {
  const obj = parseObject(data, 'Task');
  return {
    id: uuidSchema.parse(obj['id']),
    ownerId: uuidSchema.parse(obj['ownerId']),
    title: parseTitle(obj['title']),
    completed: parseBoolean(obj['completed'], 'completed'),
    createdAt: isoDateTimeSchema.parse(obj['createdAt']),
    updatedAt: isoDateTimeSchema.parse(obj['updatedAt']),
  };
});

export const createTaskRequestSchema: Schema<CreateTaskRequest> = createSchema((data: unknown) => {
  const obj = parseObject(data, 'CreateTaskRequest');
  return {
    title: parseTitle(obj['title']),
  };
});

export const updateTaskRequestSchema: Schema<UpdateTaskRequest> = createSchema((data: unknown) => {
  const obj = parseObject(data, 'UpdateTaskRequest');
  const title = parseOptional(obj['title'], parseTitle);
  const completed = parseOptional(obj['completed'], (value) => parseBoolean(value, 'completed'));
  if (title === undefined && completed === undefined) {
    throw new Error('at least one field is required');
  }
  return {
    ...(title !== undefined ? { title } : {}),
    ...(completed !== undefined ? { completed } : {}),
  };
});

export const tasksListResponseSchema: Schema<TasksListResponse> = createSchema((data: unknown) => {
  const obj = parseObject(data, 'TasksListResponse');
  return {
    tasks: createArraySchema((item: unknown) => taskSchema.parse(item)).parse(obj['tasks']),
  };
});

export const taskMutationResponseSchema: Schema<TaskMutationResponse> = createSchema(
  (data: unknown) => {
    const obj = parseObject(data, 'TaskMutationResponse');
    return {
      task: taskSchema.parse(obj['task']),
    };
  },
);
