// main/server/db/src/index.ts
/**
 * Database Package Entry Point
 *
 * Exports:
 * - Client: Raw PostgreSQL client (createRawDb, createDbClient)
 * - Schema: TypeScript types for all database tables
 * - Repositories: Data Access Layer (functional-style factories)
 * - Factory: Repository container (Repositories, createRepositories)
 * - Validation: Schema validation utilities
 * - Utils: Database helpers (case conversion, formatting)
 * - Builder: SQL query builder
 *
 * @module @bslt/db
 */

// Client
export {
  buildConnectionString,
  canReachDatabase,
  createDbClient,
  createDbFromSql,
  createRawDb,
  resolveConnectionStringWithFallback,
  type DbClient,
  type DbConfig,
  type IsolationLevel,
  type QueryOptions,
  type QueryResult,
  type RawDb,
  type SessionContext,
  type TransactionOptions,
} from './client';

// Schema
export {
  ACTIVITIES_TABLE,
  ACTIVITY_COLUMNS,
  ACTOR_TYPES,
  AGGREGATION_TYPES,
  AUDIT_CATEGORIES,
  AUDIT_EVENTS_TABLE,
  AUDIT_EVENT_COLUMNS,
  AUDIT_SEVERITIES,
  AUTH_TOKENS_TABLE,
  AUTH_TOKEN_COLUMNS,
  BILLING_EVENTS_TABLE,
  BILLING_EVENT_COLUMNS,
  BILLING_EVENT_TYPES,
  BILLING_PROVIDERS,
  CONSENT_RECORDS_TABLE,
  CONSENT_RECORD_COLUMNS,
  CONSENT_TYPES,
  CUSTOMER_MAPPINGS_TABLE,
  CUSTOMER_MAPPING_COLUMNS,
  DATA_EXPORT_REQUESTS_TABLE,
  DATA_EXPORT_REQUEST_COLUMNS,
  DATA_EXPORT_STATUSES,
  DATA_EXPORT_TYPES,
  DEFAULT_QUIET_HOURS,
  DEFAULT_TYPE_PREFERENCES,
  DOCUMENT_TYPES,
  FEATURE_FLAGS_TABLE,
  FEATURE_FLAG_COLUMNS,
  FILES_TABLE,
  FILE_COLUMNS,
  FILE_PURPOSES,
  INVITATIONS_TABLE,
  INVITATION_COLUMNS,
  INVITATION_STATUSES,
  INVOICES_TABLE,
  INVOICE_COLUMNS,
  INVOICE_STATUSES,
  CRON_JOBS_TABLE,
  JOBS_TABLE,
  JOB_COLUMNS,
  JOB_QUEUE_TABLE,
  JOB_STATUSES,
  LEGAL_DOCUMENTS_TABLE,
  LEGAL_DOCUMENT_COLUMNS,
  LOGIN_ATTEMPTS_TABLE,
  LOGIN_ATTEMPT_COLUMNS,
  MEMBERSHIPS_TABLE,
  MEMBERSHIP_COLUMNS,
  NOTIFICATIONS_TABLE,
  NOTIFICATION_COLUMNS,
  NOTIFICATION_LEVELS,
  NOTIFICATION_PREFERENCES_TABLE,
  NOTIFICATION_PREFERENCE_COLUMNS,
  OAUTH_CONNECTIONS_TABLE,
  OAUTH_CONNECTION_COLUMNS,
  OAUTH_PROVIDERS,
  PAYMENT_METHODS_TABLE,
  PAYMENT_METHOD_COLUMNS,
  PAYMENT_METHOD_TYPES,
  PLANS_TABLE,
  PLAN_COLUMNS,
  PLAN_INTERVALS,
  PUSH_SUBSCRIPTIONS_TABLE,
  PUSH_SUBSCRIPTION_COLUMNS,
  REFRESH_TOKENS_TABLE,
  REFRESH_TOKEN_COLUMNS,
  SECURITY_EVENTS_TABLE,
  SECURITY_EVENT_COLUMNS,
  SECURITY_EVENT_TYPES,
  SECURITY_SEVERITIES,
  SMS_VERIFICATION_CODES_TABLE,
  SMS_VERIFICATION_CODE_COLUMNS,
  STORAGE_PROVIDERS,
  SUBSCRIPTIONS_TABLE,
  SUBSCRIPTION_COLUMNS,
  SUBSCRIPTION_STATUSES,
  TASKS_TABLE,
  TASK_COLUMNS,
  TENANTS_TABLE,
  TENANT_COLUMNS,
  TENANT_FEATURE_OVERRIDES_TABLE,
  TENANT_FEATURE_OVERRIDE_COLUMNS,
  TENANT_ROLES,
  TENANT_SETTINGS_TABLE,
  TENANT_SETTING_COLUMNS,
  TOTP_BACKUP_CODES_TABLE,
  TOTP_BACKUP_CODE_COLUMNS,
  TRUSTED_DEVICES_TABLE,
  TRUSTED_DEVICE_COLUMNS,
  USAGE_METRICS_TABLE,
  USAGE_METRIC_COLUMNS,
  USAGE_SNAPSHOTS_TABLE,
  USAGE_SNAPSHOT_COLUMNS,
  USERS_TABLE,
  USER_COLUMNS,
  USER_SESSIONS_TABLE,
  USER_SESSION_COLUMNS,
  WEBAUTHN_CREDENTIALS_TABLE,
  WEBAUTHN_CREDENTIAL_COLUMNS,
  WEBHOOKS_TABLE,
  WEBHOOK_COLUMNS,
  WEBHOOK_DELIVERIES_TABLE,
  WEBHOOK_DELIVERY_COLUMNS,
  WEBHOOK_DELIVERY_STATUSES,
  type Activity,
  type ActorType,
  type AggregationType,
  type AuditCategory,
  type AuditEvent,
  type AuditSeverity,
  type AuthToken,
  type AuthTokenType,
  type BillingEvent,
  type BillingEventType,
  type BillingProvider,
  type CardDetails,
  type ConsentRecord,
  type ConsentRecordType,
  type ConsentType,
  type CustomerMapping,
  type DataExportRequest,
  type DataExportStatus,
  type DataExportType,
  type DocumentType,
  type FeatureFlag,
  type FilePurpose,
  type FileRecord,
  type Invitation,
  type InvitationStatus,
  type Invoice,
  type InvoiceStatus,
  type Job,
  type LegalDocument,
  type LoginAttempt,
  type Membership,
  type NewActivity,
  type NewAuditEvent,
  type NewAuthToken,
  type NewBillingEvent,
  type NewConsentRecord,
  type NewCustomerMapping,
  type NewDataExportRequest,
  type NewFeatureFlag,
  type NewFileRecord,
  type NewInvitation,
  type NewInvoice,
  type NewJob,
  type NewLegalDocument,
  type NewLoginAttempt,
  type NewMembership,
  type NewNotification,
  type NewNotificationPreference,
  type NewOAuthConnection,
  type NewPaymentMethod,
  type NewPlan,
  type NewPushSubscription,
  type NewRefreshToken,
  type NewSecurityEvent,
  type NewSmsVerificationCode,
  type NewSubscription,
  type NewTaskRecord,
  type NewTenant,
  type NewTenantCustomRole,
  type NewTenantFeatureOverride,
  type NewTenantSetting,
  type NewTotpBackupCode,
  type NewTrustedDevice,
  type NewUsageMetric,
  type NewUsageSnapshot,
  type NewUser,
  type NewUserSession,
  type NewWebauthnCredential,
  type NewWebhook,
  type NewWebhookDelivery,
  type Notification,
  type NotificationChannel,
  type NotificationLevel,
  type NotificationPreference,
  type NotificationType,
  type OAuthConnection,
  type OAuthProvider,
  type PaymentMethod,
  type PaymentMethodType,
  type Plan,
  type PlanFeature,
  type PlanInterval,
  type PushSubscription,
  type QuietHoursConfig,
  type RefreshToken,
  type RefreshTokenFamilyView,
  type SecurityEvent,
  type SecurityEventType,
  type SecuritySeverity,
  type SmsVerificationCode,
  type StorageProvider,
  type Subscription,
  type SubscriptionStatus,
  type TaskRecord,
  type Tenant,
  type TenantCustomRole,
  type TenantFeatureOverride,
  type TenantRole,
  type TenantSetting,
  type TotpBackupCode,
  type TrustedDevice,
  type TypePreferences,
  type UpdateDataExportRequest,
  type UpdateFeatureFlag,
  type UpdateFileRecord,
  type UpdateInvitation,
  type UpdateInvoice,
  type UpdateJob,
  type UpdateLegalDocument,
  type UpdateMembership,
  type UpdateNotification,
  type UpdateOAuthConnection,
  type UpdatePaymentMethod,
  type UpdatePlan,
  type UpdateSubscription,
  type UpdateTaskRecord,
  type UpdateTenant,
  type UpdateTenantCustomRole,
  type UpdateTenantFeatureOverride,
  type UpdateTenantSetting,
  type UpdateTrustedDevice,
  type UpdateUsageMetric,
  type UpdateUsageSnapshot,
  type UpdateUser,
  type UpdateUserSession,
  type UpdateWebauthnCredential,
  type UpdateWebhook,
  type UpdateWebhookDelivery,
  type UsageMetric,
  type UsageSnapshot,
  type User,
  type UserRole,
  type UserSession,
  type WebauthnCredential,
  type Webhook,
  type WebhookDelivery,
  type WebhookDeliveryStatus,
} from './schema';

// API Keys schema
export {
  API_KEY_COLUMNS,
  API_KEYS_TABLE,
  type ApiKeyAuthRecord,
  type ApiKeyRecord,
  type NewApiKeyRecord,
} from './schema';

// Analytics Events schema
export { EVENT_COLUMNS, EVENTS_TABLE, type EventRecord, type NewEventRecord } from './schema';

// Support Requests schema
export {
  SUPPORT_REQUEST_COLUMNS,
  SUPPORT_REQUESTS_TABLE,
  type NewSupportRequestRecord,
  type SupportRequestRecord,
  type SupportRequestStatus,
} from './schema';

// Repositories (functional-style)
export {
  // Activities
  createActivityRepository,
  // Audit
  createAuditEventRepository,
  // Auth tokens (unified)
  createAuthTokenRepository,
  // Billing
  createBillingEventRepository,
  // Compliance
  createConsentRecordRepository,
  createCustomerMappingRepository,
  createDataExportRequestRepository,
  // Features
  createFeatureFlagRepository,
  // Files
  createFileRepository,
  createInvitationRepository,
  createInvoiceRepository,
  createLegalDocumentRepository,
  createLoginAttemptRepository,
  createMembershipRepository,
  createNotificationPreferenceRepository,
  // In-App Notifications
  createNotificationRepository,
  // OAuth
  createOAuthConnectionRepository,
  createPaymentMethodRepository,
  createPlanRepository,
  // Push
  createPushSubscriptionRepository,
  createRefreshTokenRepository,
  createSecurityEventRepository,
  createSubscriptionRepository,
  createTaskRepository,
  createTenantFeatureOverrideRepository,
  createUsageMetricRepository,
  createUsageSnapshotRepository,
  // Tenant
  createTenantRepository,
  createTotpBackupCodeRepository,
  // Trusted Devices
  createTrustedDeviceRepository,
  // Users
  createUserRepository,
  // Sessions
  createUserSessionRepository,
  // WebAuthn Credentials
  createWebauthnCredentialRepository,
  // Types
  type ActivityRepository,
  type AdminUserListFilters,
  type AuditEventRepository,
  type AuthTokenRepository,
  type BillingEventRepository,
  type ConsentRecordRepository,
  type CursorPaginatedResult,
  type CursorPaginationOptions,
  type CustomerMappingRepository,
  type DataExportRequestRepository,
  type FeatureFlagRepository,
  type FileRepository,
  type InvitationRepository,
  type InvoiceFilters,
  type InvoiceRepository,
  type LegalDocumentRepository,
  type LoginAttemptRepository,
  type MembershipRepository,
  type NotificationPreferenceRepository,
  type NotificationRepository,
  type OAuthConnectionRepository,
  type PaymentMethodRepository,
  type PlanRepository,
  type PushSubscriptionRepository,
  type RefreshTokenRepository,
  type SecurityEventRepository,
  type SubscriptionFilters,
  type SubscriptionRepository,
  type TaskRepository,
  type TenantFeatureOverrideRepository,
  type TenantRepository,
  type TimeRangeFilter,
  type TotpBackupCodeRepository,
  type TrustedDeviceRepository,
  type UsageDelta,
  type UsageIncrementCallback,
  type UsageLimitResult,
  type UsageMetricRepository,
  type UsageSnapshotRepository,
  type UserRepository,
  type UserSessionRepository,
  type WebauthnCredentialRepository,
  type WebhookDeliveryRepository,
  type WebhookRepository,
} from './repositories';

// API Keys repository
export { createApiKeyRepository, type ApiKeyRepository } from './repositories';

// Analytics Events repository
export {
  DEFAULT_EXPORT_BATCH_SIZE,
  createEventRepository,
  type EventRepository,
} from './repositories';

// Support Requests repository
export {
  createSupportRequestRepository,
  type ListSupportRequestsOptions,
  type SupportRequestRepository,
} from './repositories';

// Factory
export {
  closeRepositories,
  createRepositories,
  getRepositoryContext,
  type Repositories,
  type RepositoryContext,
} from './factory';

// Migrations
export {
  runSqlMigrations,
  runSqlMigrationsWithDb,
  type MigrationLogger,
  type MigrationRunResult,
  type RunSqlMigrationsOptions,
  type RunSqlMigrationsWithDbOptions,
} from './migrations';

// Tenancy — schema-per-tenant isolation mechanism (opt-in via DB_TENANCY_MODE)
export {
  isValidSchemaName,
  listTenantSchemas,
  makeTenantSchemaProvisioner,
  provisionTenantSchema,
  replayPartitionedMigrations,
  resolveTenantSchema,
  TENANT_ITEMS_TABLE,
  TENANT_PARTITIONED_TABLES,
  TENANT_SCHEMA_PREFIX,
  tenantSchemaName,
  type PartitionedTable,
} from './tenancy';

// Validation
export {
  getExistingTables,
  REQUIRED_TABLES,
  requireValidSchema,
  SchemaValidationError,
  validateSchema,
  type RequiredTable,
  type SchemaValidationResult,
} from './validation';

// Utils
export {
  applyCursorPagination,
  applyOffsetPagination,
  buildColumnList,
  buildInsertClause,
  buildSetClause,
  camelizeKeys,
  camelToSnake,
  formatJsonb,
  parseJsonb,
  snakeifyKeys,
  snakeToCamel,
  toCamelCase,
  toCamelCaseArray,
  toSnakeCase,
  type ColumnMapping,
  type CountResult,
  type CursorPaginationQueryBuilder,
  type OffsetPaginationQueryBuilder,
} from './utils';

// Builder
export {
  and,
  deleteFrom,
  eq,
  escapeIdentifier,
  gt,
  gte,
  ilike,
  inArray,
  insert,
  isNotNull,
  isNull,
  lt,
  lte,
  ne,
  not,
  or,
  rawCondition,
  select,
  selectCount,
  update,
  type QueryBuilder,
  type SqlFragment,
} from './builder';

// Transaction
export { isInTransaction, withTransaction } from './utils';

// Optimistic Locking

// Queue
export {
  createPostgresQueueStore,
  PostgresQueueStore,
  WriteService,
  createWriteService,
  QueueServer,
  createQueueServer,
  MemoryQueueStore,
  createMemoryQueueStore,
  type QueueMetrics,
  type QueueServerOptions,
} from './queue';

export {
  type AfterWriteHook,
  type BeforeValidateHook,
  type JobDetails,
  type JobListOptions,
  type JobListResult,
  type JobStatus,
  type OperationResult,
  type OperationType,
  type QueueConfig,
  type QueueStats,
  type QueueStore,
  type Task,
  type TaskError,
  type TaskHandler,
  type TaskHandlers,
  type TaskResult,
  type WriteBatch,
  type WriteContext,
  type WriteError,
  type WriteHooks,
  type WriteOperation,
  type WriteResult,
  type WriteServiceOptions,
} from './queue';

// Pagination Helpers
export { createPaginationHelpers, type PaginationHelpers } from './utils/pagination.helpers';

// PubSub
export { createPostgresPubSub, PostgresPubSub } from './pubsub';
export type { PostgresPubSubOptions, PubSubMessage } from './pubsub';

// Search
export { createSqlSearchProvider, SqlSearchProvider } from './search';

export type {
  IndexHint,
  SearchContext,
  SearchMetrics,
  SearchProviderConfig,
  SearchProviderFactoryOptions,
  SearchProviderType,
  SearchResultWithMetrics,
  ServerSearchProvider,
  SqlColumnMapping,
  SqlCursorData,
  SqlFilterResult,
  SqlOperatorMap,
  SqlOperatorTranslator,
  SqlQueryOptions,
  SqlSearchProviderConfig,
  SqlTableConfig,
} from './search/types';
