// Generated by features:add / features:remove. Keep custom code outside this file.
import type { InstalledServerFeature } from './types';
export const installedFeatures: readonly InstalledServerFeature[] = [
];
